# Generated by Django 5.0.4 on 2024-04-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_customuser_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fecha_nac',
            new_name='dob',
        ),
    ]
