# Generated by Django 5.0.4 on 2024-04-28 00:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
