# Generated by Django 5.0.4 on 2024-05-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog/post/default.png', upload_to='blog/post'),
        ),
    ]
