# Generated by Django 5.0.4 on 2024-05-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('eliminado', 'Eliminado')], default='publicado', max_length=20),
        ),
    ]
